# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54dca5f8345f97e5eed6cbc9bbdf70012c58889d199eb96ae40b6ab2487e912270d95df7eaa249b190dfe8624461e9954a4b2a73f38cc4c6977aff2a1b003896

test:
  secret_key_base: 8e1e246626dd56a27f7b84bab089aabaee5bdd3cd963ce438d33d6eaecdf0014371bdc4b2797f20e5d8464df2c7f0d71ae3ca1183d9dec36ccf33c2214a59875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
